spring:
  redis:
    host: 192.168.253.101
    port: 6379
    password: abc036912
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100ms
    database: 0
